### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by mimooh** [mipmip/vim-run-in-blender#1]
It is enough to have python3 support by slight changes in your plugin:
* s/python/python3/ for imports
* s/print/print()/

I had issues with tempfile also (expected bytes not str or the other way around error), so I used static file. After all I managed to talk to blender from vim, which is cool! Thanks for the plugin!

**Comment by mimooh** [comment]
And the python/python3 imports (vim_run_in_blender.vim) is probably related to vim compiled with python3, but without python (latest ubuntu).

**Comment by mipmip** [comment]
Can you submit a pull request?

**Comment by mimooh** [comment]
I wonder if you don't need two versions, one for python2 and one for
python3 which depends on vim being compiled with python2 or python3.
What do you think? 

-- 
Karol Kreński
tel. 517-302-055

**Comment by mipmip** [comment]
Forgive for my ignorance, but I really don't know. I presume the plugin now works with python2 and and you need to have it running with python 3.

Could you make a pull request for this?

**Comment by mimooh** [comment]
> Forgive for my ignorance, but I really don't know. I presume the plugin now works with python2 and and you need to have it running with python 3.
Yes. In vim_run_in_blender.vim there's code:

	python import sys

But vim cannot execute it as vim's internal command since vim doesn't
speak python anymore (in new ubuntu I mean). Now it talks python3. 

> Could you make a pull request for this?
Let me play more with this blender + vim setup. It is likely I would
extend your script to have blender output errors redirected to vim - you
know, catching those "look on the console now" errors that blender
outputs to the terminal, to another place than vim itself, which is
unconvenient.

What worries me is I ran into problems with vim + blender scripting :(
The same script pasted to internal blender editor works fine, but run
via vim-blender skips large number of commands. Have you experienced
that? I may want to inspect that.

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment]
I assume you are a vim+blender user since you authored this script. I have just started to gather the information about blender+external editors and there's more than this plugin. I heard the blender API is not directly visible outside of blender (needed to autocomplete blender objects in vim), but there's that awesome guy who just made the API exporter! It can be downloaded at http://airplanes3d.net/pydev-000_e.xml (pydev-blender.zip archive). I am about to inspect how we can have this plugged to vim and then have even greater plugin.

**Comment by mipmip** [comment]
You might want to read this thread on stackexchange: http://blender.stackexchange.com/questions/41533/how-to-remotely-run-a-python-script-in-an-existing-blender-instance

**Comment by mimooh** [comment]
I've seen that one, yes. Seems like I learned about all the approaches there are for having vim and blender work together - the access to bpy API is the main issue and the main desire. If I come up with something I will let you know. I will at least try, since I cannot do without vim for most of what I do :)

**Comment by mipmip** [comment]
closing this one
