### ISSUE TITLE
Segmentation fault executing code

### ISSUE THREAD

**Issue by ovitus** [mipmip/vim-run-in-blender#6]
awright@x1yoga:~/blender$ blender
Read prefs: /home/awright/.config/blender/2.90/config/userpref.blend
found bundled python: /opt/blender-2.90.1-linux64/2.90/python
2020-09-25 01:18:56,860     INFO bpy_externall-master Entering modal operator...
Writing: /tmp/blender.crash.txt
Segmentation fault

I attached the [blender.crash.txt](https://github.com/mipmip/vim-run-in-blender/files/5280736/blender.crash.txt). This is from executing the following with :RunInBlender
```
import bpy

bpy.ops.mesh.primitive_cube_add()
```

**Comment by mipmip** [comment]
Is this still occuring in latest Blender versions?
